- include_vars: group_vars/users.yml

- name: Add users | create users, shell, home dirs
  become: yes
  user: 
    name: "{{ item.username }}"
    shell: /bin/bash 
    createhome: yes 
    comment: 'create with ansible'
  with_items: 
    - "{{users}}"

- name: Setup | authorized key upload
  become: yes
  authorized_key: 
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'files/{{ item.username }}.pub') }}"
  with_items: "{{users}}"

- name: Sudoers | update sudoers file and validate
  become: yes
  lineinfile: 
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
    regexp: '^{{ item.username }} .*'
    state: present
  when: 
    item.use_sudo == True
  with_items: 
    - "{{users}}"